### ISSUE TITLE
where's  www.clash-lang.org ?

### ISSUE THREAD

**Issue by postoroniy** [clash-lang/clash-lang.github.io#8]
Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.clash-lang.org.

**Comment by martijnbastiaan** [comment]
What does `nslookup www.clash-lang.org` look like for you?

**Comment by postoroniy** [comment]
Non-authoritative answer:
Name:	www.clash-lang.org
Address: 13.236.188.46

**Comment by postoroniy** [comment]
hm...just tried one more time and can load clash-lang.org

**Comment by martijnbastiaan** [comment]
We should have changed our DNS to time-out after 5 minutes, wait 24 hours, and THEN change the settings but we forgot. What you saw as probably a propagation issue. Glad it's solved!
